---
engines:
  duplication:
    exclude_paths:
      - 'packages/playwright/tests/*.spec.*'
      - 'packages/playwright/tests/**/*.spec.*'
      - 'packages/cypress/tests/cypress/e2e/*.cy.*'
      - 'packages/cypress/tests/cypress/e2e/**/*.cy.*'
      - 'packages/**/*.test.*'
      
