packages:
  - "packages/*"
allowBuilds:
  "@swc/core": true
  cypress: true
  esbuild: true
  msw: true
minimumReleaseAgeExclude:
  - "@vitest/browser-playwright@5.0.0"
  - "@vitest/browser@5.0.0"
  - "@vitest/coverage-v8@5.0.0"
  - "@vitest/mocker@5.0.0"
  - "@vitest/pretty-format@5.0.0"
  - "@vitest/spy@5.0.0"
  - "@vitest/ui@5.0.0"
  - "@vitest/utils@5.0.0"
  - vitest@5.0.0
