packages:
  - 'packages/*'
allowBuilds:
  '@swc/core': true
  cypress: true
  esbuild: true
  msw: true

# Required for scripts/prepare-embedded.ts to work
nodeLinker: hoisted
hoistingLimits: workspaces
