import { test, expect, takeSnapshot } from '../src';

test.only('same-origin embed page loads', async ({ page }, testInfo) => {
  await page.goto('/embeds/same-origin');

  await takeSnapshot(page, 'One', testInfo);
  await new Promise((resolve) => setTimeout(resolve, 100));
  await takeSnapshot(page, 'Two', testInfo);
  await new Promise((resolve) => setTimeout(resolve, 100));
  await takeSnapshot(page, 'Three', testInfo);
  await new Promise((resolve) => setTimeout(resolve, 100));
  await takeSnapshot(page, 'Four', testInfo);
  await new Promise((resolve) => setTimeout(resolve, 100));
  await takeSnapshot(page, 'Five', testInfo);
});

test.describe('', () => {
  test.use({ assetDomains: ['http://localhost:3001'] });

  test('cross-origin embed page loads', async ({ page }) => {
    await page.goto('/embeds/cross-origin');
    await expect(page.getByRole('heading', { name: 'Embeds' })).toBeVisible();
    await expect(page.locator('iframe[title="Cross-origin iframe"]')).toBeVisible();
    await expect(
      page.frameLocator('iframe[title="Cross-origin iframe"]').getByText('Embedded page')
    ).toBeVisible();
  });

  test('nested iframes', async ({ page }) => {
    await page.goto('/embeds/nested-pages');
    await expect(page.getByRole('heading', { name: 'Top page' })).toBeVisible();

    await expect(
      page.frameLocator('iframe[title="First iframe"]').getByText('Embeds')
    ).toBeVisible();

    await expect(
      page.frameLocator('iframe[title="Second iframe"]').getByText('Embeds')
    ).toBeVisible();
  });
});

test.describe('', () => {
  // since we're manually taking snapshots after each button click we don't need another snapshot at the end
  // (and we certainly don't want a snapshot with an autogenerated name)
  test.use({ disableAutoSnapshot: true, assetDomains: ['http://localhost:3001'] });

  for (const origin of ['same-origin', 'cross-origin'] as const) {
    test(`embedded page background color can be changed (${origin})`, async ({
      page,
    }, testInfo) => {
      await page.goto(`/embeds/${origin}`);
      await expect(page.getByRole('heading', { name: 'Embeds' })).toBeVisible();

      const title = origin === 'same-origin' ? 'Same-origin' : 'Cross-origin';
      const embedded = page.frameLocator(`iframe[title="${title} iframe"]`);

      await expect(embedded.getByRole('heading', { name: 'Embedded page' })).toBeVisible();

      await embedded.getByRole('button', { name: 'Red' }).click();
      await expect(embedded.locator('body')).toHaveCSS('background-color', 'rgb(255, 0, 0)');
      await takeSnapshot(page, 'Red background', testInfo);

      await embedded.getByRole('button', { name: 'Yellow' }).click();
      await expect(embedded.locator('body')).toHaveCSS('background-color', 'rgb(255, 255, 0)');
      await takeSnapshot(page, 'Yellow background', testInfo);

      await embedded.getByRole('button', { name: 'Blue' }).click();
      await expect(embedded.locator('body')).toHaveCSS('background-color', 'rgb(0, 0, 255)');
      await takeSnapshot(page, 'Blue background', testInfo);

      await embedded.getByRole('button', { name: 'Reset' }).click();
      await expect(embedded.locator('body')).toHaveCSS('background-color', 'rgba(0, 0, 0, 0)');
      await takeSnapshot(page, 'Reset background', testInfo);

      await embedded.getByRole('button', { name: 'Green on Hover' }).hover();
      await expect(embedded.locator('body')).toHaveCSS('background-color', 'rgb(0, 128, 0)');
      await takeSnapshot(page, 'Green background on hover', testInfo);
    });
  }
});
