import { test, expect, takeSnapshot } from '../src';

test('snapshot names increment for both manual and automatic', async ({ page }, testInfo) => {
  await page.goto('/manual-snapshots');
  await takeSnapshot(page, testInfo);
  await page.locator('summary').click();
  await expect(page.getByText('I am hiding inside!')).toBeVisible();
  await takeSnapshot(page, 'another test', testInfo);
  await takeSnapshot(page, testInfo);
});

test.describe('', () => {
  test.use({ disableAutoSnapshot: true });
  test('manual snapshot is taken even when automatic snapshots are turned off', async ({
    page,
  }, testInfo) => {
    await page.goto('/manual-snapshots');
    await takeSnapshot(page, 'accordion collapsed', testInfo);
    await page.locator('summary').click();
    await expect(page.getByText('I am hiding inside!')).toBeVisible();
  });

  test('manual snapshot name autogenerated when not passed', async ({ page }, testInfo) => {
    await page.goto('/manual-snapshots');
    await takeSnapshot(page, testInfo);
    await page.locator('summary').click();
    await expect(page.getByText('I am hiding inside!')).toBeVisible();
  });
});
