import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { existsSync, readFileSync } from 'node:fs';
import type { StorybookConfig } from '@storybook/server-webpack5';
import type { Compiler } from 'webpack';
import { archivesDir } from '@chromatic-com/shared-e2e/utils/filePaths';
import { DEFAULT_OUTPUT_DIR } from '../constants';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Resolve embedded Storybook 10.x stack from package root (dist/storybook-config -> .. -> ..)
const packageRoot = path.resolve(__dirname, '..', '..');
const embeddedDir = path.join(packageRoot, 'embedded', 'node_modules');

export default <StorybookConfig>{
  stories: [path.resolve(archivesDir(DEFAULT_OUTPUT_DIR), '*.stories.json')],
  managerEntries: [path.resolve(__dirname, 'manager.js')],
  previewAnnotations: [path.resolve(__dirname, 'preview.js')],
  framework: {
    name: path.join(embeddedDir, '@storybook', 'server-webpack5'),
    options: {},
  },
  core: {
    // ESM does not support directory imports; point to the package entry file.
    builder: pathToFileURL(
      path.join(embeddedDir, '@storybook', 'builder-webpack5', 'dist', 'index.js')
    ).href,
    renderer: pathToFileURL(path.join(embeddedDir, '@storybook', 'server', 'preset.js')).href,
  },
  staticDirs: [path.resolve(archivesDir(DEFAULT_OUTPUT_DIR), 'archive')],
  features: {
    sidebarOnboardingChecklist: false,
  },
  webpackFinal: async (config) => {
    // Webpack defaults to `target: 'browserslist'`, which makes 'storybook build' transform
    // files based on the user's `.browserslistrc`: https://webpack.js.org/configuration/target/
    config.target = ['web'];

    config.plugins.push(new VitestStatsPlugin());

    return config;
  },
};

class VitestStatsPlugin {
  apply(compiler: Compiler) {
    const chromaticResults = path.dirname(archivesDir(DEFAULT_OUTPUT_DIR));
    const previewStats = path.resolve(chromaticResults, 'preview-stats.json');

    if (existsSync(previewStats)) {
      compiler.hooks.done.tap('Vitest Stats Plugin', (stats) => {
        const { modules } = JSON.parse(readFileSync(previewStats, 'utf-8'));
        const json = stats.toJson();

        /**
         * Append test modules generated by {@link file://./../node/webpack-stats-reporter.ts} into
         * Webpack's actual modules. The Story JSON files are already present there.
         */
        stats.toJson = () => ({ ...json, modules: [...json.modules, ...modules] });
      });
    }
  }
}
