import { expect } from 'vitest';
import { page } from 'vitest/browser';
import { test } from './utils/browser';
import { disableAutoSnapshot, takeSnapshot } from '../dist';

test.override({ url: '/manual-snapshots' });

test('snapshot names increment for both manual and automatic', async () => {
  await takeSnapshot();
  await page.getByText('Click me').click();
  expect(page.getByText('I am hiding inside!')).toBeVisible();

  await takeSnapshot('another test');
  await takeSnapshot();
});

test('manual snapshot is taken even when automatic snapshots are turned off', async () => {
  disableAutoSnapshot();

  await takeSnapshot('accordion collapsed');

  await page.getByText('Click me').click();
  expect(page.getByText('I am hiding inside!')).toBeVisible();
});

test('manual snapshot name autogenerated when not passed', async () => {
  disableAutoSnapshot();

  await takeSnapshot();

  await page.getByText('Click me').click();
  expect(page.getByText('I am hiding inside!')).toBeVisible();
});
