import { expect } from 'vitest';
import { page } from 'vitest/browser';
import { test } from './utils/browser';
import { takeSnapshot } from '../dist';

test.override({ url: '/manual-snapshots' });

test('snapshot names increment for both manual and automatic', async () => {
  await takeSnapshot();
  await page.getByText('Click me').click();
  expect(page.getByText('I am hiding inside!')).toBeVisible();

  await takeSnapshot('another test');
  await takeSnapshot();
});

test.todo('manual snapshot is taken even when automatic snapshots are turned off');

test.todo('manual snapshot name autogenerated when not passed');
