import { expect } from "vitest";
import { page } from "vitest/browser";

import { configure, takeSnapshot } from "../dist";
import { test } from "./utils/browser";

test.override({ url: "/manual-snapshots" });

test("snapshot names increment for both manual and automatic", async () => {
  await takeSnapshot();
  await page.getByText("Click me", { exact: false }).click();
  expect(page.getByText("I am hiding inside!", { exact: false })).toBeVisible();

  await takeSnapshot("another test");
  await takeSnapshot();
});

test("manual snapshot is taken even when automatic snapshots are turned off", async () => {
  configure({ disableAutoSnapshot: true });

  await takeSnapshot("accordion collapsed");

  await page.getByText("Click me", { exact: false }).click();
  expect(page.getByText("I am hiding inside!", { exact: false })).toBeVisible();
});

test("manual snapshot name autogenerated when not passed", async () => {
  configure({ disableAutoSnapshot: true });

  await takeSnapshot();

  await page.getByText("Click me", { exact: false }).click();
  expect(page.getByText("I am hiding inside!", { exact: false })).toBeVisible();
});
