import { randomUUID } from 'node:crypto';
import { appendFile, mkdir } from 'node:fs/promises';
import { resolve } from 'node:path';
import { isCI, nodeVersion } from 'std-env';
import type { Vitest } from 'vitest/node';
import { version as pluginVersion } from '../../../package.json';
import {
  EVENT_TYPE_PREFIX,
  TELEMETRY_FETCH_TIMEOUT_MS,
  TELEMETRY_LOG_FILE,
  TELEMETRY_URL,
} from './constants';
import { getEnv, isDisabledByEnv } from './env';
import {
  createProjectId,
  getChromaticVersion,
  packageManager,
  readTelemetryMetadata,
  writeTelemetryMetadata,
} from './metadata';
import { sanitizeError } from './sanitize';
import { session } from './session';
import type { EventType, TelemetryEvent, WireTelemetryEvent } from './types';
import type { ResolvedOptions } from '../../types';

/**
 * Track a telemetry event. Attaches all automatically generated fields.
 */
export function trackEvent<T extends EventType = EventType>(
  event: TelemetryEvent<T>,
  vitest: Vitest,
  options: ResolvedOptions
): void {
  if (!options.telemetry.enabled) {
    return;
  }

  const promise = _trackEvent(event, vitest, options)
    .catch(() => {})
    .finally(() => session.cleanups.delete(promise));

  session.cleanups.add(promise);
}

/**
 * Track a telemetry event from the CLI. Attaches metadata and autogenerated fields automatically.
 */
export async function trackCliEvent<T extends EventType = EventType>(
  event: TelemetryEvent<T>,
  options: { outputDirectory: string }
): Promise<void> {
  if (isDisabledByEnv()) {
    return;
  }

  let telemetryMetadata = session.telemetryMetadata;

  if (session.telemetryMetadata === undefined) {
    telemetryMetadata = await readTelemetryMetadata(options.outputDirectory);
    session.telemetryMetadata = telemetryMetadata;

    if (!('disabled' in telemetryMetadata)) {
      session.id = telemetryMetadata.sessionId;
      session.projectId = telemetryMetadata.projectId;
      session.chromaticVersion = telemetryMetadata.chromaticVersion;
    }
  }

  // If we don't find telemetry metadata written by Vitest test run, we consider telemetry to be disabled.
  if (!telemetryMetadata || 'disabled' in telemetryMetadata) {
    return;
  }

  await _trackEvent(
    event,
    {
      version: telemetryMetadata.vitestVersion || 'unknown',
      config: { root: options.outputDirectory },
      projects: telemetryMetadata.isVitestProjects ? [1, 2] : [],
    },
    {
      outputDirectory: options.outputDirectory,
      telemetry: { enabled: true, logToFile: telemetryMetadata.logToFile },
    }
  );
}

async function _trackEvent(
  event: TelemetryEvent,
  vitest: {
    version: Vitest['version'];
    config: Pick<Vitest['config'], 'root'>;
    projects: unknown[];
  },
  options: Pick<ResolvedOptions, 'outputDirectory' | 'telemetry'>
) {
  const url = getEnv('CHROMATIC_TELEMETRY_URL') || TELEMETRY_URL;
  const root = vitest.config.root;
  const timestamp = new Date().toISOString();
  const outputDirectory = resolve(root, options.outputDirectory);

  session.projectId ||= await createProjectId(root);
  session.chromaticVersion ||= getChromaticVersion(root);

  const wireEvent: WireTelemetryEvent = {
    id: randomUUID(),
    sessionId: session.id,
    projectId: session.projectId,
    timestamp,
    eventType: `${EVENT_TYPE_PREFIX}${event.eventType}`,
    level: event.level,
    payload: event.payload,
    metadata: {
      isCI,
      pluginVersion,
      nodeVersion: nodeVersion || 'unknown',
      vitestVersion: vitest.version,
      isVitestProjects: vitest.projects.length > 1,
      packageManager: packageManager.name,
      packageManagerVersion: packageManager.version,
      chromaticVersion: session.chromaticVersion,
    },
  };

  if (wireEvent.level === 'error' && 'error' in wireEvent.payload) {
    wireEvent.payload.error = sanitizeError(wireEvent.payload.error);
  }

  let error: string | undefined = undefined;

  try {
    await fetch(`${url}/telemetry/v1/vitest/events`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(wireEvent),
      signal: AbortSignal.timeout(TELEMETRY_FETCH_TIMEOUT_MS),
    });
  } catch (err) {
    error = err instanceof Error ? err.message : String(err);
  }

  if (options.telemetry.logToFile) {
    const logFile = resolve(outputDirectory, TELEMETRY_LOG_FILE);

    await mkdir(outputDirectory, { recursive: true });
    await appendFile(logFile, `${JSON.stringify(wireEvent)}\n`, 'utf8');

    if (error) {
      await appendFile(logFile, `${JSON.stringify({ telemetryPostError: error })}\n`, 'utf8');
    }
  }

  if (!session.isMetadataWritten) {
    session.isMetadataWritten = true;

    await writeTelemetryMetadata(outputDirectory, {
      ...wireEvent.metadata,
      sessionId: wireEvent.sessionId,
      projectId: wireEvent.projectId,
      logToFile: options.telemetry.logToFile,
    });
  }
}
