name: Test and Release PR

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  test:
    uses: ./.github/workflows/test-base.yml
  test_cypress:
    needs: test
    uses: ./.github/workflows/test-cypress.yml
    secrets:
       chromaticProjectToken: ${{ secrets.CHROMATIC_CYPRESS_PROJECT_TOKEN }}
  test_playwright:
    needs: test
    uses: ./.github/workflows/test-playwright.yml
    secrets:
       chromaticProjectToken: ${{ secrets.CHROMATIC_PLAYWRIGHT_PROJECT_TOKEN }}
  release_canary:
    needs: test
    uses: ./.github/workflows/canary-release.yml
    secrets:
      githubToken: ${{ secrets.GITHUB_TOKEN }}
      npmToken: ${{ secrets.NPM_PUBLISH_TOKEN }}
    