# Workflow for PR branches
# Runs the test workflows and the canary release workflow
name: Test and Release PR

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo skipping everything'
