# Runs the main changeset release process
# This has two phases:
# 1. When a PR is merged that contains changesets, a PR will
#    be opened with package.json version bumps and changelog updates
# 2. When the above PR with the package.json version bumps is merged,
#    the changed packages will then be published to npm
name: Release

on:
  workflow_call:
    secrets:
      githubToken:
        required: true
      npmToken:
        required: true
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'

      - name: Install Dependencies
        run: yarn install

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          publish: yarn run release
        env:
          GITHUB_TOKEN: ${{ secrets.githubToken }}
          NODE_AUTH_TOKEN: ${{ secrets.npmToken }}