name: Test (Playwright)

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.workflow_run.head_branch }}

      - name: Use Node.js 18.x
        uses: actions/setup-node@v1
        with:
          node-version: 18.x

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Install Playwright
        run: |
          yarn playwright install

      - name: Build
        run: |
          yarn run build

      - name: Run tests
        run: |
          yarn run test:playwright

      - name: Publish to Chromatic
        uses: chromaui/action@canary
        with:
          projectToken: ${{ secrets.CHROMATIC_PLAYWRIGHT_PROJECT_TOKEN }}
          playwright: true
