# Runs linting and unit tests
name: Test Base

on:
  workflow_call:
    secrets:
      codacyProjectToken:
        required: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use Node.js 18.x
        uses: actions/setup-node@v1
        with:
          node-version: 18.x

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Install Playwright
        run: |
          yarn playwright install

      - name: Build
        run: |
          yarn run build

      # - name: Run lint
      #   run: |
      #     yarn run lint

      # - name: Run tests
      #   run: |
      #     yarn run test:unit

      # - name: Report code coverage to Codacy
      #   run: |
      #     bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r packages/cypress/coverage/lcov.info -r packages/playwright/coverage/lcov.info -r packages/shared/coverage/lcov.info
      #   env:
      #     CODACY_PROJECT_TOKEN: ${{ secrets.codacyProjectToken }}
