name: Test Base

on: workflow_call

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use Node.js 18.x
        uses: actions/setup-node@v1
        with:
          node-version: 18.x

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Install Playwright
        run: |
          yarn playwright install    

      - name: Build
        run: |
          yarn run build

      - name: Run lint
        run: |
          yarn run lint

      - name: Run tests
        run: |
          yarn run test:unit