name: Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install dependencies
        run: pnpm install

      - name: Install Playwright
        run: |
          pnpm playwright install

      - name: Run lint
        run: |
          pnpm lint

      - name: Run tests
        run: |
          pnpm test:unit
          pnpm test:playwright

      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_ARCHIVE_PROJECT_TOKEN }}
          buildScriptName: build-archive-storybook
